### ISSUE TITLE
ElMessiri -> El Messiri ?

### ISSUE THREAD

**Issue by davelab6** [Gue3bara/El-Messiri#4]
In https://github.com/Gue3bara/ElMessiri/commit/baea2f338e919e6d368b200a5a4784fe866a58f8 `El-Messiri` was changed to `ElMessiri` but I think it should be `El Messiri` everywhere instead

**Comment by Gue3bara** [comment]
will do that

**Comment by Gue3bara** [comment]
@davelab6 when i export the font Glyphs automatically removed the space so it ends up being "ElMessiri" instead of "El Messiri" should i manually fix that?
also when i name the project "El Messiri" github replaces the space with "-" so it's now "El-Messiri" 

so it's "El-Messiri" on github because github dose that 
and "ElMessiri" font file because of Glyphs

**Comment by Gue3bara** [comment]
@davelab6 can you tell me what's the right form to do now 
is this issue fixed now?

**Comment by davelab6** [comment]
Looks ok now :)
